import jsPDF from 'jspdf';

interface ReportData {
  totalEmployees: number;
  activeEmployees: number;
  presentToday: number;
  revenue: number;
  expenses: number;
  profit: number;
}

export function exportDashboardPdf(
  data: ReportData
) {
  const pdf = new jsPDF();

  pdf.setFontSize(20);
  pdf.text(
    'AMDOX ERP - BI Report',
    20,
    20
  );

  pdf.setFontSize(11);

  pdf.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    30
  );

  pdf.line(20, 35, 190, 35);

  pdf.setFontSize(14);

  pdf.text(
    'Business Intelligence Summary',
    20,
    50
  );

  pdf.setFontSize(12);

  pdf.text(
    `Total Employees: ${data.totalEmployees}`,
    20,
    65
  );

  pdf.text(
    `Active Employees: ${data.activeEmployees}`,
    20,
    75
  );

  pdf.text(
    `Present Today: ${data.presentToday}`,
    20,
    85
  );

  pdf.text(
    `Revenue: ₹${data.revenue.toLocaleString()}`,
    20,
    105
  );

  pdf.text(
    `Expenses: ₹${data.expenses.toLocaleString()}`,
    20,
    115
  );

  pdf.text(
    `Profit: ₹${data.profit.toLocaleString()}`,
    20,
    125
  );

  pdf.line(20, 135, 190, 135);

  pdf.setFontSize(10);

  pdf.text(
    'Generated by AMDOX ERP Business Intelligence Module',
    20,
    150
  );

  pdf.save('amdox-bi-report.pdf');
}