import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import PDFDocument from 'pdfkit';
import { Response } from 'express';

@Injectable()
export class PayrollService {
  constructor(private prisma: PrismaService) {}

  async generatePayroll(data: any) {
    const employee = await this.prisma.employee.findUnique({
      where: {
        id: data.employeeId,
      },
    });

    if (!employee) {
      throw new Error('Employee not found');
    }

    // Count absent days
    const absentCount = await this.prisma.attendance.count({
      where: {
        employeeId: employee.id,
        status: 'absent',
      },
    });

    const basicSalary = employee.salary;

    // Per day salary
    const perDaySalary = basicSalary / 30;

    // Deduction calculation
    const autoDeduction = absentCount * perDaySalary;

    const bonus = data.bonus || 0;

    const manualDeductions = data.deductions || 0;

    const totalDeductions = autoDeduction + manualDeductions;

    const netSalary = basicSalary + bonus - totalDeductions;

    return this.prisma.payroll.create({
      data: {
        month: data.month,
        basicSalary,
        bonus,
        deductions: totalDeductions,
        netSalary,
        employeeId: employee.id,
      },
    });
  }

  async findAll() {
    return this.prisma.payroll.findMany({
      include: {
        employee: true,
      },
    });
  }

  async getMyPayroll(user: any) {
    const employee = await this.prisma.employee.findFirst({
      where: {
        userId: user.userId,
      },
    });

    if (!employee) {
      throw new Error('Employee not found');
    }

    return this.prisma.payroll.findMany({
      where: {
        employeeId: employee.id,
      },
    });
  }

  async generatePayslip(payrollId: number, res: Response) {
    const payroll = await this.prisma.payroll.findUnique({
      where: {
        id: payrollId,
      },
      include: {
        employee: true,
      },
    });

    if (!payroll) {
      throw new Error('Payroll not found');
    }

    const doc = new PDFDocument();

    // Response headers
    res.setHeader('Content-Type', 'application/pdf');

    res.setHeader(
      'Content-Disposition',
      `attachment; filename=payslip-${payroll.id}.pdf`,
    );

    doc.pipe(res);

    // Title
    doc.fontSize(22).text('Employee Payslip', {
      align: 'center',
    });

    doc.moveDown();

    // Employee details
    doc.fontSize(14).text(`Employee Name: ${payroll.employee.name}`);

    doc.text(`Department: ${payroll.employee.department}`);

    doc.text(`Position: ${payroll.employee.position}`);

    doc.moveDown();

    // Payroll details
    doc.text(`Month: ${payroll.month}`);
    doc.text(`Basic Salary: ₹${payroll.basicSalary}`);

    doc.text(`Bonus: ₹${payroll.bonus}`);

    doc.text(`Deductions: ₹${payroll.deductions}`);

    doc.moveDown();

    // Net Salary
    doc.fontSize(16).text(`Net Salary: ₹${payroll.netSalary}`);

    doc.moveDown();

    doc.text('Generated by AI Powered Cloud ERP', {
      align: 'center',
    });

    doc.end();
  }
}
